name: Publish Python package
on:
  push:
    tags: ['*']          # every git tag triggers a release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      # lets the job upload to the Packages registry
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build wheel & sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish to GitHub Packages
        env:
          # injected automatically – you never define this yourself
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload dist/
